spec/v2/examples/invalid-response-all-properties.json
spec/v2/examples/list-footprints-response.json
spec/v2/index.bs

(see the tech spec's changelog section for additional details)

docs(spec v2): fixes to 2 discrepancies between this specs and Pathfinder Framework

---

spec/index.bs
spec/v2/index.bs

Summary of the changes can be found in the v2 specs changelog

New Version 2.0.1-20230522 with 1 definition fix

---

spec/v2/index.bs

Fixes 5 definition incorrectness and adds 5 clarifications. See the changelog within the `spec/v2/index.bs` file for details.

 New Version 2.0.1-20230623

---

spec/v2/index.bs

see changelog for details of this PR

docs(spec v2): clarify unit of `fossilCarbonContent` and `biogenicCarbonContent`

---

spec/v2/index.bs

see additional changelog added to `spec/v2/index.bs`

chore(spec v2): clarification to specs of properties `fossilGhgEmissions`, `pCfExcludingBiogenic`, `pCfIncludingBiogenic`, `biogenicCarbonWithdrawal`

---

spec/v2/index.bs

Situation:
The specification was not sufficiently clear on error handling of the Action Authenticate endpoint.
Additionally, with this change the section on error responses is further updated.

feat (spec v2): clarifications on error response handling, specifically for Action Authenticate

---

DECISION-MAKING-PROCESS.md
README.md
RELEASE-PLAN.md

Summary of changes:
1. contribution process moved into dedicated file
2. added release plan file
3. plus added links to both above to the README.md

feat: release plan documentation

---

decisions/log/0026-async-request-by-default.md
spec/v2/index.bs

Based on the discussion at https://github.com/wbcsd/data-exchange-protocol/pull/30. 
This PR includes:
- The original ADR proposed by @wern
- The changes to the Technical Specifications based on that ADR and approved in the January 17 Tech WG call

ADR0026 - Action Events becomes Mandatory

---

decisions/log/0027-footprint-fragment.md
spec/v2/index.bs

This PR continues the discussion started in [PR45](https://github.com/wbcsd/data-exchange-protocol/pull/45) and, as agreed in the February 28 Tech WG call, is now in consultation phase (and thus subject to further change).

ADR0027 (Consultation phase)

---

spec/v2/index.bs

fix: wrong EXTENSIONS-GUIDANCE link

---

spec/v2/index.bs

This adds an important `Note` to the beginning of chapter 4 plus a generic introduction.

introduction to chapter 4 / business cases

---

decisions/log/0031-mandatory-to-optional-attributes.md

I am raising ADR 0031 to reflect discussions and decisions being made in the Tech and Methodology Working Groups to consider changing several attributes from Mandatory to Optional.
Final decision pending consensus vote in the Methodology Working Group, March 21. I will update this ADR once consensus has been reached.
Note that I have not included the respective changes to the Tech Specs (v2.2 and v3) in this PR / ADR. @zeitgeist  and @raimundo-henriques once we reach final consensus, would be great if you could propose those changes along with this ADR.

ADR0031 Mandatory to optional attributes

---

spec/v2/index.bs

@marleyg, thanks for your feedback. Here's the PR based on it. Can you please review it?
Thank you!

Clarification on how to handle error codes in ListResponseBody and GetResponseBody

---

spec/header.include
spec/index.bs

Makes the v1 Tech Specs  use the v2-style header

chore: update v1.0.1 to follow the v2 header style; fix linking

---

spec/v2/index.bs

With this PR I am hoping to better understand the process to make tech specs changes!

Fix broken link to Vision Paper

---

.github/workflows/pages.yml
DECISION-MAKING-PROCESS.md
RELEASE-INSTRUCTIONS.md
decisions/log/0012-request-response-patterns.md
decisions/log/0014-request-response-patterns.md
decisions/log/0017-life-cycle-status-property-additional-rules.md
decisions/log/0019-increment-pcf-endpoints-version.md
decisions/log/0021-openid-base-auth.md
decisions/log/0026-async-request-by-default.md
decisions/log/0027-footprint-fragment.md
decisions/log/0028-provide-clarity-on-characterization-factors.md
decisions/log/README.md
spec/faq/index.bs
spec/index.bs
spec/v2/index.bs

Corrects a number of minor typos and spelling errors as well as a minor grammar error.

Typo fix-ups

---

spec/v2/diagrams/events.mmd
spec/v2/index.bs

feat: include events UML diagram

---

decisions/log/0032-cross-sectoral-standards.md
spec/v2/index.bs

We accidentally closed the previous PR for the ADR on cross sectoral standards, so we are now opening this new one. For previous discussions, refer to #69

ADR32 Extend Cross Sectoral Standards

---

spec/v2/index.bs

Includes a changelog entry update and a fix to the changelog entries' version numbers

Update email, editor, and former editors

---

decisions/log/0034-common-urn-structure-productIDs.md
spec/v2/index.bs

Proposal for definition of Product and Company identifiers.

ADR 0034 Proposal for a common URN structure for identifying products

---

.github/workflows/pages.yml

Adapted GH workflow to the new Makefile and output directory (/build)

Adapted .github page publish workflow

---

decisions/log/0046-include-ccu.md
spec/v3/openapi.yaml

Proposal to add 3 properties to the CarbonFootprint data model for 3.0, for reporting on Carbon Capture and Usage.

ADR46 - Include attributes for CCU

---

scripts/excel.py
spec/v3/openapi.yaml

As presented in the combined Tech/Metholodogy working group 26 March

Proposed changes to biogenic attributes and ccs
